#include "\a3\3DEN\UI\resincl.inc"
#include "\a3\3DEN\UI\macros.inc"
#define pixelScale	1.25
#define pixelGrid 4
#define PANEL_W	60
#define MENUBAR_H	SIZE_M
#define TOOLBAR_H	(SIZE_M + 2)
#define TAB_H	(SIZE_M + 1)
#define STATUSBAR_W	(safezoneW - PANEL_W * GRID_W)
#define STATUSBAR_H	SIZE_S
#define CONTROLSHINT_W	50
#define PLAYBUTTON_H	10
#define NAV_H		15
#define TRANSPARENT_A	0.87
#define GRID_W (pixelW * pixelScale * pixelGrid)
#define GRID_H (pixelH * pixelScale * pixelGrid)